CONFIGDIR="$HOME/.config"
export WORKSPACE="$HOME/code"
export DOTFILES="$WORKSPACE/.dotfiles"
export ZDOTDIR="$CONFIGDIR/zsh"
export EMACSDIR="$CONFIGDIR/emacs"

export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

export EDITOR="emacsclient -nw"
export VISUAL="emacsclient"

export PATH="$HOME/.local/bin/:$HOME/baga/includes/:/usr/local/go/bin:$HOME/go/bin:$HOME/bin/:$PATH"

. "$HOME/.cargo/env"
